name: Build APK
on: [push]
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip autoconf libtool pkg-config zlib1g-dev libncurses5-dev cmake libffi-dev libssl-dev
        pip install buildozer cython kivy yt-dlp

    - name: Accept licenses
      run: |
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true

    - name: Build APK
      run: |
        export ANDROIDSDK=$ANDROID_HOME
        export ANDROIDNDK=$ANDROID_NDK
        export ANDROIDAPI=33
        export ANDROIDMINAPI=21
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: VideoDownloader-by-annamehndi31
        path: bin/*.apk
